# Generated by Django 6.0.5 on 2026-05-31 08:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_first_name_user_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyVerseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(help_text='URL-friendly identifier', unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Daily Verse Categories',
                'db_table': 'daily_verse_categories',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='DailyVerse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('verse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_verse_entries', to='core.verse')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verses', to='core.dailyversecategory')),
            ],
            options={
                'db_table': 'daily_verses',
                'ordering': ['category', 'id'],
                'indexes': [models.Index(fields=['category'], name='daily_verse_categor_c235fb_idx'), models.Index(fields=['verse'], name='daily_verse_verse_i_99859c_idx')],
                'unique_together': {('category', 'verse')},
            },
        ),
    ]
