# Generated by Django 5.2.15 on 2026-06-06 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_create_default_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookaudio',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio', to='core.book'),
        ),
    ]
