# Generated by Django 4.2.7 on 2026-06-06 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_bookaudio_foreignkey'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='names', to='core.book')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_names', to='core.language')),
            ],
            options={
                'db_table': 'book_names',
                'ordering': ['book__bible_order'],
                'unique_together': {('book', 'language')},
            },
        ),
    ]
