# Generated by Django 5.2.15 on 2026-06-06 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_seed_book_names'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersession',
            name='token',
        ),
        migrations.AddField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AddField(
            model_name='usersession',
            name='token_hash',
            field=models.CharField(max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='bible_order',
            field=models.IntegerField(default=0, help_text='Order in the Bible (1–66)'),
        ),
        migrations.AlterField(
            model_name='book',
            name='has_audio',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='book',
            name='total_chapters',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='total_verses',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='chapteraudio',
            name='chapter_number',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='chapteraudio',
            name='end_time',
            field=models.IntegerField(blank=True, help_text='End time in seconds within full-book audio', null=True),
        ),
        migrations.AlterField(
            model_name='chapteraudio',
            name='start_time',
            field=models.IntegerField(default=0, help_text='Start time in seconds within full-book audio'),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='resume_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userbookprogress',
            name='audio_completed_chapters',
            field=models.JSONField(default=list, help_text='Chapter numbers completed via audio'),
        ),
    ]
